# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
