# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_friend_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
